package cal.constants

enum class CurrencyCode(val code: String, val fullName: String, val symbol: String) {
    AED(CurrenciesConstants.AED, "United Arab Emirates Dirham", "د.إ"),
    AFN(CurrenciesConstants.AFN, "Afghan Afghani", "؋"),
    ALL(CurrenciesConstants.ALL, "Albanian Lek", "L"),
    ARS(CurrenciesConstants.ARS, "Argentine Peso", "$"),
    AUD(CurrenciesConstants.AUD, "Australian Dollar", "A$"),
    AWG(CurrenciesConstants.AWG, "Aruban Florin", "ƒ"),
    AZN(CurrenciesConstants.AZN, "Azerbaijani Manat", "₼"),
    BDT(CurrenciesConstants.BDT, "Bangladeshi Taka", "৳"),
    BGN(CurrenciesConstants.BGN, "Bulgarian Lev", "лв"),
    BHD(CurrenciesConstants.BHD, "Bahraini Dinar", ".د.ب"),
    BOB(CurrenciesConstants.BOB, "Bolivian Boliviano", "Bs."),
    BRL(CurrenciesConstants.BRL, "Brazilian Real", "R$"),
    CAD(CurrenciesConstants.CAD, "Canadian Dollar", "C$"),
    CHF(CurrenciesConstants.CHF, "Swiss Franc", "CHF"),
    CLP(CurrenciesConstants.CLP, "Chilean Peso", "$"),
    CNY(CurrenciesConstants.CNY, "Chinese Yuan", "¥"),
    COP(CurrenciesConstants.COP, "Colombian Peso", "$"),
    CRC(CurrenciesConstants.CRC, "Costa Rican Colón", "₡"),
    CZK(CurrenciesConstants.CZK, "Czech Koruna", "Kč"),
    DKK(CurrenciesConstants.DKK, "Danish Krone", "kr"),
    DZD(CurrenciesConstants.DZD, "Algerian Dinar", "دج"),
    EGP(CurrenciesConstants.EGP, "Egyptian Pound", "£"),
    EUR(CurrenciesConstants.EUR, "Euro", "€"),
    FJD(CurrenciesConstants.FJD, "Fijian Dollar", "FJ$"),
    GBP(CurrenciesConstants.GBP, "British Pound Sterling", "£"),
    GEL(CurrenciesConstants.GEL, "Georgian Lari", "₾"),
    GHS(CurrenciesConstants.GHS, "Ghanaian Cedi", "₵"),
    HKD(CurrenciesConstants.HKD, "Hong Kong Dollar", "HK$"),
    HRK(CurrenciesConstants.HRK, "Croatian Kuna", "kn"),
    HUF(CurrenciesConstants.HUF, "Hungarian Forint", "Ft"),
    IDR(CurrenciesConstants.IDR, "Indonesian Rupiah", "Rp"),
    ILS(CurrenciesConstants.ILS, "Israeli New Shekel", "₪"),
    INR(CurrenciesConstants.INR, "Indian Rupee", "₹"),
    IQD(CurrenciesConstants.IQD, "Iraqi Dinar", "ع.د"),
    ISK(CurrenciesConstants.ISK, "Icelandic Krona", "kr"),
    JOD(CurrenciesConstants.JOD, "Jordanian Dinar", "JD"),
    JPY(CurrenciesConstants.JPY, "Japanese Yen", "¥"),
    KES(CurrenciesConstants.KES, "Kenyan Shilling", "KSh"),
    KRW(CurrenciesConstants.KRW, "South Korean Won", "₩"),
    KWD(CurrenciesConstants.KWD, "Kuwaiti Dinar", "KD"),
    KZT(CurrenciesConstants.KZT, "Kazakhstani Tenge", "₸"),
    LBP(CurrenciesConstants.LBP, "Lebanese Pound", "ل.ل"),
    LKR(CurrenciesConstants.LKR, "Sri Lankan Rupee", "Rs"),
    MAD(CurrenciesConstants.MAD, "Moroccan Dirham", "د.م."),
    MDL(CurrenciesConstants.MDL, "Moldovan Leu", "L"),
    MMK(CurrenciesConstants.MMK, "Myanmar Kyat", "Ks"),
    MNT(CurrenciesConstants.MNT, "Mongolian Tögrög", "₮"),
    MOP(CurrenciesConstants.MOP, "Macanese Pataca", "MOP$"),
    MXN(CurrenciesConstants.MXN, "Mexican Peso", "$"),
    MYR(CurrenciesConstants.MYR, "Malaysian Ringgit", "RM"),
    NGN(CurrenciesConstants.NGN, "Nigerian Naira", "₦"),
    NOK(CurrenciesConstants.NOK, "Norwegian Krone", "kr"),
    NZD(CurrenciesConstants.NZD, "New Zealand Dollar", "NZ$"),
    OMR(CurrenciesConstants.OMR, "Omani Rial", "﷼"),
    PEN(CurrenciesConstants.PEN, "Peruvian Sol", "S/."),
    PHP(CurrenciesConstants.PHP, "Philippine Peso", "₱"),
    PKR(CurrenciesConstants.PKR, "Pakistani Rupee", "₨"),
    PLN(CurrenciesConstants.PLN, "Polish Zloty", "zł"),
    PYG(CurrenciesConstants.PYG, "Paraguayan Guarani", "₲"),
    QAR(CurrenciesConstants.QAR, "Qatari Riyal", "﷼"),
    RON(CurrenciesConstants.RON, "Romanian Leu", "lei"),
    RSD(CurrenciesConstants.RSD, "Serbian Dinar", "дин."),
    RUB(CurrenciesConstants.RUB, "Russian Ruble", "₽"),
    SAR(CurrenciesConstants.SAR, "Saudi Riyal", "﷼"),
    SEK(CurrenciesConstants.SEK, "Swedish Krona", "kr"),
    SGD(CurrenciesConstants.SGD, "Singapore Dollar", "S$"),
    THB(CurrenciesConstants.THB, "Thai Baht", "฿"),
    TRY(CurrenciesConstants.TRY, "Turkish Lira", "₺"),
    TWD(CurrenciesConstants.TWD, "New Taiwan Dollar", "NT$"),
    TZS(CurrenciesConstants.TZS, "Tanzanian Shilling", "TSh"),
    UAH(CurrenciesConstants.UAH, "Ukrainian Hryvnia", "₴"),
    USD(CurrenciesConstants.USD, "United States Dollar", "$"),
    VEF(CurrenciesConstants.VEF, "Venezuelan Bolívar (Old)", "Bs"),
    VND(CurrenciesConstants.VND, "Vietnamese Dong", "₫"),
    ZAR(CurrenciesConstants.ZAR, "South African Rand", "R");

    companion object {
        fun fromCode(code: String): CurrencyCode? =
            values().find { it.code.equals(code, ignoreCase = true) }
    }
}
