package cal.constants


object CurrenciesConstants {
    const val AED = "AED"
    const val AFN = "AFN"
    const val ALL = "ALL"
    const val ARS = "ARS"
    const val AUD = "AUD"
    const val AWG = "AWG"
    const val AZN = "AZN"
    const val BDT = "BDT"
    const val BGN = "BGN"
    const val BHD = "BHD"
    const val BOB = "BOB"
    const val BRL = "BRL"
    const val CAD = "CAD"
    const val CHF = "CHF"
    const val CLP = "CLP"
    const val CNY = "CNY"
    const val COP = "COP"
    const val CRC = "CRC"
    const val CZK = "CZK"
    const val DKK = "DKK"
    const val DZD = "DZD"
    const val EGP = "EGP"
    const val EUR = "EUR"
    const val FJD = "FJD"
    const val GBP = "GBP"
    const val GEL = "GEL"
    const val GHS = "GHS"
    const val HKD = "HKD"
    const val HRK = "HRK"
    const val HUF = "HUF"
    const val IDR = "IDR"
    const val ILS = "ILS"
    const val INR = "INR"
    const val IQD = "IQD"
    const val ISK = "ISK"
    const val JOD = "JOD"
    const val JPY = "JPY"
    const val KES = "KES"
    const val KRW = "KRW"
    const val KWD = "KWD"
    const val KZT = "KZT"
    const val LBP = "LBP"
    const val LKR = "LKR"
    const val MAD = "MAD"
    const val MDL = "MDL"
    const val MMK = "MMK"
    const val MNT = "MNT"
    const val MOP = "MOP"
    const val MXN = "MXN"
    const val MYR = "MYR"
    const val NGN = "NGN"
    const val NOK = "NOK"
    const val NZD = "NZD"
    const val OMR = "OMR"
    const val PEN = "PEN"
    const val PHP = "PHP"
    const val PKR = "PKR"
    const val PLN = "PLN"
    const val PYG = "PYG"
    const val QAR = "QAR"
    const val RON = "RON"
    const val RSD = "RSD"
    const val RUB = "RUB"
    const val SAR = "SAR"
    const val SEK = "SEK"
    const val SGD = "SGD"
    const val THB = "THB"
    const val TRY = "TRY"
    const val TWD = "TWD"
    const val TZS = "TZS"
    const val UAH = "UAH"
    const val USD = "USD"
    const val VEF = "VEF"
    const val VND = "VND"
    const val ZAR = "ZAR"

    val all_Con = listOf(
        AED, AFN, ALL, ARS, AUD, AWG, AZN, BDT, BGN, BHD, BOB, BRL, CAD, CHF, CLP,
        CNY, COP, CRC, CZK, DKK, DZD, EGP, EUR, FJD, GBP, GEL, GHS, HKD, HRK, HUF,
        IDR, ILS, INR, IQD, ISK, JOD, JPY, KES, KRW, KWD, KZT, LBP, LKR, MAD, MDL,
        MMK, MNT, MOP, MXN, MYR, NGN, NOK, NZD, OMR, PEN, PHP, PKR, PLN, PYG, QAR,
        RON, RSD, RUB, SAR, SEK, SGD, THB, TRY, TWD, TZS, UAH, USD, VEF, VND, ZAR
    )
}
